name: Addictions
author: cannoli_cat
version: 2.0.1
main: cannolicat.addictions.Addictions
api-version: '1.20'
softdepend: [MythicMobs]
commands:
  addAddiction:
    description: Add an addiction to a player!
    permission: addiction.add
    usage: /<command> <player> <addiction>
  removeAddiction:
    description: Remove an addiction from a player!
    permission: addiction.remove
    usage: /<command> <player> <addiction>
  clearAddictions:
    description: Removes all addictions from a player!
    permission: addiction.remove
    usage: /<command> <player>
  showAddictions:
    description: View a players current addictions!
    permission: addiction.show
    usage: /<command> <player>
  updatedate:
    description: Update an addictions time since last use for a player!
    permission: addiction.update
    usage: /<command> <player> <addiction>
  addictionReload:
    description: Reloads the plugin
    permission: addiction.admin
    usage: /<command>